"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


[aws]
style = "bold #ffb86c"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
truncate_to_repo = true

[gcloud]
disabled = true

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[time]
disabled = false

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"

[character]
success_symbol = "[λ](bold #f8f8f2)"
error_symbol = "[λ](bold #ff5555)"
